### ISSUE TITLE
ModuleNotFoundError: No module named 'Hinkskalle.util'

### ISSUE THREAD

**Issue by grisuthedragon** [csf-ngs/hinkskalle#31]
In the current containers, downloaded by docker compose, the follwoing error is thrown:

```
# flask db upgrade
Usage: flask db upgrade [OPTIONS] [REVISION]
Try 'flask db upgrade --help' for help.

Error: While importing 'Hinkskalle', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 234, in locate_app
    __import__(module_name)
  File "/usr/local/lib/python3.8/dist-packages/Hinkskalle/__init__.py", line 17, in <module>
    from Hinkskalle.util.swagger import register_authenticators
ModuleNotFoundError: No module named 'Hinkskalle.util'


```

**Comment by h3kker** [comment]
Thanks for reporting this, the `working_dir` option was not set in the example docker-compose.
