### ISSUE TITLE
Tag has multiple architectures exception

### ISSUE THREAD

**Issue by h3kker** [csf-ngs/hinkskalle#47]
Hard to reproduce, but this keeps popping up at vbcf after some push (running v4.3.1):

```
api_1           | [2022-09-23 09:01:51,044] ERROR in app:1455 | Exception on /v1/latest [GET]
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask_rebar/compat.py", line 44, in dump
api_1           |     result = schema.dump(data)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 552, in dump
api_1           |     result = self._serialize(processed_obj, many=many)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 520, in _serialize
api_1           |     value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 338, in serialize
api_1           |     return self._serialize(value, attr, obj, **kwargs)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 634, in _serialize
api_1           |     return schema.dump(nested_obj, many=many)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 552, in dump
api_1           |     result = self._serialize(processed_obj, many=many)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 514, in _serialize
api_1           |     return [
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 515, in <listcomp>
api_1           |     self._serialize(d, many=False)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 520, in _serialize
api_1           |     value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 338, in serialize
api_1           |     return self._serialize(value, attr, obj, **kwargs)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 634, in _serialize
api_1           |     return schema.dump(nested_obj, many=many)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 552, in dump
api_1           |     result = self._serialize(processed_obj, many=many)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 520, in _serialize
api_1           |     value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 330, in serialize
api_1           |     value = self.get_value(obj, attr, accessor=accessor)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 260, in get_value
api_1           |     return accessor_func(obj, check_key, default)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 479, in get_attribute
api_1           |     return get_value(obj, attr, default)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/utils.py", line 241, in get_value
api_1           |     return _get_value_for_key(obj, key, default)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/marshmallow/utils.py", line 255, in _get_value_for_key
api_1           |     return getattr(obj, key, default)
api_1           |   File "/srv/hinkskalle/backend/Hinkskalle/models/Container.py", line 174, in imageTags
api_1           |     raise Exception(f"Tag {[tag.name](http://tag.name/)} has multiple architectures")
api_1           | Exception: Tag 0.21.0-asm294v2 has multiple architectures
api_1           | During handling of the above exception, another exception occurred:
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1523, in full_dispatch_request
api_1           |     rv = self.dispatch_request()
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1509, in dispatch_request
api_1           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask_rebar/rebar.py", line 164, in wrapped
api_1           |     marshaled = marshal(data=data, schema=schema)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask_rebar/utils/request_utils.py", line 91, in marshal
api_1           |     return compat.dump(schema=schema, data=data)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask_rebar/compat.py", line 48, in dump
api_1           |     raise marshmallow.ValidationError(str(e))
api_1           | marshmallow.exceptions.ValidationError: Tag 0.21.0-asm294v2 has multiple architectures
```

**Comment by h3kker** [comment]
problem: singularity container can have the same tag pointing to different images iff they have different architectures (e.g. `ppc` and `amd64`. Typically I think (esp on the vbc) you'd only have amd64 images.

In this particular case I think there must be a non-arch tag for `0.21.0-asm294v2` (tag.arch is null). By pushing `0.21.0-asm294v2` again (with a newer client, against a newer Hinkskalle version) an arch-specific tag was created. Bug: Hinkskalle did not move the existing tag, but created a second one. @idot quick fix is to delete one of the `0.21.0-asm294v2` tags directly in the `tag` table (with arch is null or pointing to an image with arch is null).

Hinkskalle did not support arch specific tags from the beginning. The singularity library protocol has `/v1/tags` for non-architecture-specific tags and `/v2/tags` for arch tags. Even if there is only one arch used, ever, there might still be non-arch tags also lurking about (from older clients, previous Hinkskalle versions).

problems:

1. try to tag with an arch specific tag that is already there as non-arch tag -> creates a second tag
2. `imageTags` is broken, it always fails if there is >1 tag with the same name (also for different, valid architectures), and `imageTags` is always called when serializing a container
3. mix of arch and non-arch tags

fix 1. is a philosophical question: should the non-arch tag be replaced by the first arch tag that comes around? IDK, partial solution: if arch tag is `DEFAULT_ARCH`: replace, else: leave alone
fix 2. again no guidance in the specs; I think: show only default arch tags
fix 3. by setting `DEFAULT_ARCH` on the /v1/tags routes.
