### ISSUE TITLE
Integer out of Range when uploading large Images

### ISSUE THREAD

**Issue by grisuthedragon** [csf-ngs/hinkskalle#51]
When we upload a large image (around 14 GB), hinkskalle returns a HTTP 500 and we get the following output in the log: 

```
hinkdb_1        | 2023-01-24 12:50:34.094 UTC [47] ERROR:  integer out of range
hinkdb_1        | 2023-01-24 12:50:34.094 UTC [47] STATEMENT:  INSERT INTO image_upload_url (id, "expiresAt", path, size, md5sum, sha256sum, state, type, "partNumber", "totalParts", "createdAt", "createdBy", parent_id, image_id) VALUES ('35b54ce4-2a61-41c9-83f9-25713125b8f8', '2023-01-24T12:55:34.094330'::timestamp, '/mnt/images/_tmp/tmp61ddtvmq', 14068015104, NULL, NULL, 'initialized', 'multipart', NULL, 210, '2023-01-24T12:50:34.094355'::timestamp, 'koehlerm', NULL, 35)
api_1           | [2023-01-24 12:50:34,097] ERROR in app:1449 | Exception on /v2/imagefile/35/_multipart [POST]
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
api_1           |     self.dialect.do_execute(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
api_1           |     cursor.execute(statement, parameters)
api_1           | psycopg2.errors.NumericValueOutOfRange: integer out of range
api_1           | 
api_1           | 
api_1           | The above exception was the direct cause of the following exception:
api_1           | 
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
api_1           |     rv = self.dispatch_request()
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
api_1           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/flask_rebar/rebar.py", line 141, in wrapped
api_1           |     rv = f(*args, **kwargs)
api_1           |   File "/srv/hinkskalle/backend/Hinkskalle/routes/imagefiles.py", line 231, in push_image_v2_multi_init
api_1           |     db.session.commit()
api_1           |   File "<string>", line 2, in commit
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1451, in commit
api_1           |     self._transaction.commit(_to_root=self.future)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 829, in commit
api_1           |     self._prepare_impl()
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
api_1           |     self.session.flush()
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 3429, in flush
api_1           |     self._flush(objects)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 3569, in _flush
api_1           |     transaction.rollback(_capture_exception=True)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
api_1           |     compat.raise_(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
api_1           |     raise exception
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 3529, in _flush
api_1           |     flush_context.execute()
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
api_1           |     rec.execute(self)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
api_1           |     util.preloaded.orm_persistence.save_obj(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
api_1           |     _emit_insert_statements(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
api_1           |     result = connection._execute_20(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
api_1           |     return meth(self, args_10style, kwargs_10style, execution_options)
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
api_1           |     return connection._execute_clauseelement(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
api_1           |     ret = self._execute_context(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
api_1           |     self._handle_dbapi_exception(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
api_1           |     util.raise_(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
api_1           |     raise exception
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
api_1           |     self.dialect.do_execute(
api_1           |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
api_1           |     cursor.execute(statement, parameters)
api_1           | sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range
api_1           | 
api_1           | [SQL: INSERT INTO image_upload_url (id, "expiresAt", path, size, md5sum, sha256sum, state, type, "partNumber", "totalParts", "createdAt", "createdBy", parent_id, image_id) VALUES (%(id)s, %(expiresAt)s, %(path)s, %(size)s, %(md5sum)s, %(sha256sum)s, %(state)s, %(type)s, %(partNumber)s, %(totalParts)s, %(createdAt)s, %(createdBy)s, %(parent_id)s, %(image_id)s)]
api_1           | [parameters: {'id': '35b54ce4-2a61-41c9-83f9-25713125b8f8', 'expiresAt': datetime.datetime(2023, 1, 24, 12, 55, 34, 94330), 'path': '/mnt/images/_tmp/tmp61ddtvmq', 'size': 14068015104, 'md5sum': None, 'sha256sum': None, 'state': 'initialized', 'type': 'multipart', 'partNumber': None, 'totalParts': 210, 'createdAt': datetime.datetime(2023, 1, 24, 12, 50, 34, 94355), 'createdBy': 'koehlerm', 'parent_id': None, 'image_id': 35}]
api_1           | (Background on this error at: https://sqlalche.me/e/14/9h9h)
```

Running Hinkskalle 4.6.0 upgrade from 4.4.x. 

Some details: 

In models/Image.py the `size` column is created as 
```python 
size = db.Column(db.BigInteger())
```
but looking at the table in the postgres db we get:
```
hinkskalle=# \d image_upload_url
                      Table "public.image_upload_url"
   Column   |            Type             | Collation | Nullable | Default 
------------+-----------------------------+-----------+----------+---------
 id         | character varying           |           | not null | 
 expiresAt  | timestamp without time zone |           |          | 
 path       | character varying           |           | not null | 
 size       | integer                     |           |          | 
 md5sum     | character varying           |           |          | 
 sha256sum  | character varying           |           |          | 
 state      | character varying           |           |          | 
 createdAt  | timestamp without time zone |           |          | 
 createdBy  | character varying           |           |          | 
 image_id   | integer                     |           | not null | 
 type       | upload_types                |           |          | 
 parent_id  | character varying           |           |          | 
 partNumber | integer                     |           |          | 
 totalParts | integer                     |           |          | 
```
This results in a 4 byte integer column. 

The reason seems that during the update to 4.6. the db migrations are not executed. For now, I did it manually: 
```
docker exec -it hinkskalle_hinkdb_1 psql -U XXXXX -d hinkskalle
alter table image_upload_url alter column size TYPE BIGINT;
alter table image alter column size TYPE BIGINT;
```

Either we're missing something during upgrade or the migration does not work properly.  
@h3kker I think, a short "upgrade" section in the docs would be nice.

**Comment by h3kker** [comment]
Hm, this is in migration [176eef8ffb6a](https://github.com/csf-ngs/hinkskalle/blob/master/backend/migrations/versions/176eef8ffb6a_size_column_bigint.py) from 2021-05-07 15:56:45.293212.

Either it does not do what it should or something got messed up with the migrations in your case... Anyways, thanks for the suggestion, I will update the docs with a hint!
